ALTER TABLE SCHOOL.TEXTKEY_APPLICATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCHOOL.TEXTKEY_APPLICATION CASCADE CONSTRAINTS;

CREATE TABLE SCHOOL.TEXTKEY_APPLICATION
(
  TEXTKEY_APPLICATION_ID  NUMBER                NOT NULL,
  TEXTKEY_ID_FK           NUMBER                NOT NULL,
  APPLIKATION_ID_FK       NUMBER                NOT NULL,
  MASKE                   VARCHAR2(100 BYTE),
  POSITIONX               NUMBER,
  POSITIONY               NUMBER,
  MAXIMALE_BREITE         NUMBER,
  KENNZEICHENMASKE        VARCHAR2(100 BYTE),
  INSUSER                 VARCHAR2(20 BYTE),
  INSDATE                 DATE,
  INSPRGM                 VARCHAR2(20 BYTE),
  INSVERSION              VARCHAR2(20 BYTE),
  UPDUSER                 VARCHAR2(20 BYTE),
  UPDDATE                 DATE,
  UPDPRGM                 VARCHAR2(20 BYTE),
  UPDVERSION              VARCHAR2(20 BYTE),
  SATZSTATUS              VARCHAR2(1 BYTE),
  SIMPLE_KEY              VARCHAR2(100 BYTE)
)

ALTER TABLE SCHOOL.TEXTKEY_APPLICATION ADD (
  CONSTRAINT TEXTKEY_APPLICATION_PK
  PRIMARY KEY
  (TEXTKEY_APPLICATION_ID)
);

ALTER TABLE SCHOOL.TEXTKEY_APPLICATION ADD (
  CONSTRAINT TEXTKEY_APP_TEXTKEY_FK 
  FOREIGN KEY (TEXTKEY_ID_FK) 
  REFERENCES SCHOOL.TEXTKEY (TEXTKEY_ID)
  ON DELETE CASCADE
  DEFERRABLE INITIALLY IMMEDIATE
  ENABLE VALIDATE);

